"""Shared, cross-cutting infrastructure for obsidian-bible-import."""

from .constants import (
    ROOT_PATH,
    DATA_PATH,
    BIBLES_PATH,
    OUTPUT_PATH,
    SUPPORTED_TRANSLATIONS,
    TRANSLATION_ORDER,
)
from .utils import (
    to_bool,
    to_int,
    read_json,
    clean_text,
)
from .markdown import (
    FRONTMATTER_DELIMITER,
    YAML_LIST_PREFIX,
    BULLET_PREFIX,
    yaml_quote,
    format_field,
    wikilink,
    quoted_wikilink,
    heading,
    bullet_link,
    bullet_links,
    section,
    yaml_link_field,
    yaml_list,
    yaml_link_list,
    frontmatter,
    render_note,
)
from .references import (
    book_ref,
    chapter_ref,
    verse_ref_alias,
    verse_ref_file,
    verse_ref_link,
    build_alias_names,
    chapter_aliases,
    verse_aliases,
)

__all__ = [
    "ROOT_PATH",
    "DATA_PATH",
    "BIBLES_PATH",
    "OUTPUT_PATH",
    "SUPPORTED_TRANSLATIONS",
    "TRANSLATION_ORDER",
    "to_bool",
    "to_int",
    "read_json",
    "clean_text",
    "FRONTMATTER_DELIMITER",
    "YAML_LIST_PREFIX",
    "BULLET_PREFIX",
    "yaml_quote",
    "format_field",
    "wikilink",
    "quoted_wikilink",
    "heading",
    "bullet_link",
    "bullet_links",
    "section",
    "yaml_link_field",
    "yaml_list",
    "yaml_link_list",
    "frontmatter",
    "render_note",
    "book_ref",
    "chapter_ref",
    "verse_ref_alias",
    "verse_ref_file",
    "verse_ref_link",
    "build_alias_names",
    "chapter_aliases",
    "verse_aliases",
]
